# This file was generated by GoReleaser. DO NOT EDIT.
cask "oc" do
  name "oc"
  desc "The OpenCode Launcher"
  homepage "https://github.com/kayden-kim/oc"
  version "0.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "oc"

  on_macos do
    on_intel do
      url "https://github.com/kayden-kim/oc/releases/download/v#{version}/oc_#{version}_Darwin_x86_64.tar.gz",
        verified: "github.com/kayden-kim/oc/"
      sha256 "db5f2de566dc70983f14b751761ae78c372d920b95f7571388605a46ce181acd"
    end
    on_arm do
      url "https://github.com/kayden-kim/oc/releases/download/v#{version}/oc_#{version}_Darwin_arm64.tar.gz",
        verified: "github.com/kayden-kim/oc/"
      sha256 "4f73b9a2b091a2c7a2a0bf8afd536d0b0d16e1324c40ecb976b2bcabc2231bcb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kayden-kim/oc/releases/download/v#{version}/oc_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/kayden-kim/oc/"
      sha256 "85528417cab6abfa9bc0a6ad0e0f17783ad601458c1f87e578199c9ca9d29b1d"
    end
    on_arm do
      url "https://github.com/kayden-kim/oc/releases/download/v#{version}/oc_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/kayden-kim/oc/"
      sha256 "c80871538ddd80f8cf675897331e638ae5115f088e6043ca40065d0e06a5892c"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/oc"]
    end
  end

  # No zap stanza required
end
