# This file was generated by GoReleaser. DO NOT EDIT.
cask "oc" do
  name "oc"
  desc "The OpenCode Launcher"
  homepage "https://github.com/kayden-kim/oc"
  version "0.3.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "oc"

  on_macos do
    on_intel do
      url "https://github.com/kayden-kim/oc/releases/download/v#{version}/oc_#{version}_Darwin_x86_64.tar.gz",
        verified: "github.com/kayden-kim/oc/"
      sha256 "c55c46304b90a068fa03901f4ca6950d7db921d51c294fde15fe0e8b407049a4"
    end
    on_arm do
      url "https://github.com/kayden-kim/oc/releases/download/v#{version}/oc_#{version}_Darwin_arm64.tar.gz",
        verified: "github.com/kayden-kim/oc/"
      sha256 "1ee812d72fa34459d3f62e53d4ed9e29881d5f1286e1ecf57330a7f342cf70cd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kayden-kim/oc/releases/download/v#{version}/oc_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/kayden-kim/oc/"
      sha256 "2f96a8d8c794c0c8685ffd45bf5a354cc6689533544eed53c3a3a87cdfb7c377"
    end
    on_arm do
      url "https://github.com/kayden-kim/oc/releases/download/v#{version}/oc_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/kayden-kim/oc/"
      sha256 "6459a697fcddaa815c74b8df10a7480ee8cf1a8cb4f80126af9e6e3275831cd0"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/oc"]
    end
  end

  # No zap stanza required
end
