# This file was generated by GoReleaser. DO NOT EDIT.
cask "oc" do
  name "oc"
  desc "The OpenCode Launcher"
  homepage "https://github.com/kayden-kim/oc"
  version "0.2.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "oc"

  on_macos do
    on_intel do
      url "https://github.com/kayden-kim/oc/releases/download/v#{version}/oc_#{version}_Darwin_x86_64.tar.gz",
        verified: "github.com/kayden-kim/oc/"
      sha256 "78da2745f8c9a0bd4999c9667a1dfa2cd1ed33eadd40d55cdbd05e2ca647cac2"
    end
    on_arm do
      url "https://github.com/kayden-kim/oc/releases/download/v#{version}/oc_#{version}_Darwin_arm64.tar.gz",
        verified: "github.com/kayden-kim/oc/"
      sha256 "d4a5e5eef14589ee393f82ee85a9377524972f76311e442580c9b6133b5bc86b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kayden-kim/oc/releases/download/v#{version}/oc_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/kayden-kim/oc/"
      sha256 "df2658917da206860f292a1fc8baed5305f12f58ef635216d75ebb4a17991bac"
    end
    on_arm do
      url "https://github.com/kayden-kim/oc/releases/download/v#{version}/oc_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/kayden-kim/oc/"
      sha256 "f4ab785ee91901f23cfd98277f0f163e053f559cb1f44058520cdd40d0414927"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/oc"]
    end
  end

  # No zap stanza required
end
